name: Run Conformance Tests

on:
  # TODO: Trigger on release events too.
  workflow_dispatch:
    inputs:
      image-variant:
        description: "The image variant to use."
        required: true
        type: choice
        options:
          - standard
          - distroless
      version:
        description: "Optional: Specify an existing Gloo Gateway release tag to deploy and test (e.g., 1.17.3). Leave empty to use the default branch."
        required: false
        type: string

jobs:
  run-conformance-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # TODO(tim): Avoid hardcoding versions here. It's a bit tricky based on
        # how this was setup and there's a limited # of dispatch inputs that GH
        # supports. We can revisit this later.
        kube-version:
        - node: 'v1.31.0@sha256:53df588e04085fd41ae12de0c3fe4c72f7013bba32a20e7325357a1ac94ba865'
          kubectl: 'v1.31.0'
          kind: 'v0.24.0'
          helm: 'v3.14.4'
        image-variant:
          - ${{ inputs.image-variant }}
        version:
          - ${{ inputs.version }}
        version-files:
          - label: 'min'
            file: './.github/workflows/.env/pr-tests/min_versions.env'
          - label: 'max'
            file: './.github/workflows/.env/pr-tests/max_versions.env'
    steps:
      # Checkout the branch that initiated the action
      - name: Checkout Repository
        uses: actions/checkout@v4
      # The dotenv action is used to load key-value pairs from files.
      # In this case, the file is specified in the matrix and will contain the versions of the tools to use
      - name: Dotenv Action
        uses: falti/dotenv-action@v1.1.4
        id: dotenv
        with:
          path: ${{ matrix.version-files.file }}
          log-variables: true
      # Run the k8s gateway api conformance tests
      - name: Run Conformance Tests
        uses: ./.github/workflows/composite-actions/kube-gateway-api-conformance-tests
        with:
          k8sgateway-api-version: ${{ steps.dotenv.outputs.k8sgateway_api_version }}
      # TODO(tim): Add support for downloading the test results and creating
      # a pull request whenever a new release > 1.17+ is cut.
